### ISSUE TITLE
Update test.txt with the topic you are learning

### ISSUE THREAD

**Issue by nbkhope** [nbktechworld/introduction-to-git#1]
Edit the file `test.txt` and add a line saying what you are studying/learning right now. If you want, (optional) feel free to leave your GitHub @ handle there as well.

**Comment by nbkhope** [comment]
Hey, I want to help out. Can you assign me to this issue?

**Comment by MDSCLLC** [comment]
Hey, I want to help out...TY

**Comment by rendertolearn** [comment]
can you please sign me to help out!
